admc_user_homepage:
    path:     /
    defaults: { _controller: ADMCUserBundle:User:index }
    
admcdsi_request_view:
    path:     /view
    defaults: { _controller: ADMCDSIBundle:Dsi:requestsview }

admcuser_request_own_list:
    path:     /userlist
    defaults: { _controller: ADMCUserBundle:User:requestsOwnList }