admcuser_homepage:
    path:     /
    defaults: { _controller: ADMCUserBundle:User:index }
    

admcuser_request_own_list:
       path:    /modify
       defaults: { _controller: ADMCUserBundle:User:requestsOwnList}
    
admcuser_request_networkdrive_view:
    path: /network
    defaults: { _controller: ADMCUserBundle:User:requestNetwork }

admcuser_request_software_view:
    path: /software
    defaults: { _controller: ADMCUserBundle:User:requestSoftware}
    
admcuser_software_request_created:
    path: /requestSoftwareDone
    defaults: { _controller: ADMCUserBundle:User:requestSoftwareCreated}
    
admcuser_network_request_created:
    path: /requestNetworkDone
    defaults: { _controller: ADMCUserBundle:User:requestNetworkCreated}
    
admcuser_request_list:
    path: /list
    defaults: { _controller: ADMCUserBundle:User:requestsview}
    
admcuser_request_refresh_list2:
    path:     /listRefresh
    defaults: { _controller: ADMCUserBundle:User:requestList }
    
admcuser_request_consult:
    path:     /consultRequest/?{id}
    defaults: { _controller: ADMCUserBundle:User:consultRequest }
    
admcuser_delete_request:
    path: /deleteRequest/{id}
    defaults: { _controller:ADMCUserBundle:User:deleteRequest }
