admcuser_homepage:
    path:     /
    defaults: { _controller: ADMCUserBundle:User:index }
    

admcuser_request_own_list:
       path:    /modify
       defaults: { _controller: ADMCUserBundle:User:requestsOwnList}
    
admcuser_request_networkdrive_view:
    path: /
    defaults: { _controller: ADMCUserBundle:User:requestNetwork }

admcuser_request_software_view:
    path: /
    defaults: { _controller: ADMCUserBundle:User:requestSoftware}
