imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ADMCCoreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - LexikFormFilterBundle:Form:form_div_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ADMC\CoreBundle\Entity\User
    group:
        group_class: ADMC\CoreBundle\Entity\Group
        
        
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig 
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
        
fr3d_ldap:
    driver:
       host:     192.168.1.240
       username: jmiller@admc.com
       password: Password123
       accountDomainName: admc.com
       
    user:
        baseDn: cn=Users,dc=admc,dc=com
        filter: (&(ObjectClass=Person))
        attributes:
            - { ldap_attr: samaccountname,  user_method: setUsername }
#    service:
#        #fr3d_ldap.user_hydrator.default
#        #ldap_manager:  app.ldap.ldap_manager
        
        
#fr3d_ldap:
#    driver:
#       host:     ldap.forumsys.com
#       port:     389
#       bindRequiresDn:      true
#       baseDn:   cn=read-only-admin,dc=example,dc=com
#       password: password
#    user:
#        baseDn: dc=example,dc=com
#        filter: (&(objectClass=person))
#        attributes:
#           - { ldap_attr: uid,  user_method: setUsername }
#           - { ldap_attr: mail, user_method: setEmail }
  #  service:
    #    ldap_manager:  app.ldap.ldap_manager
    
    
    
    
#fr3d_ldap:
#    driver:
#        host:                192.168.1.240
#        port:                389    # Optional
#        username:            gabin    # Optional
#        password:            Donjon2016    # Optional
#        bindRequiresDn:      true   # Optional
#        baseDn:               dc=admc, dc=com   # Optional
#       accountFilterFormat: (&(uid=%s)) # Optional. sprintf format %s will be the username
#       optReferrals:        false  # Optional
#       useSsl:              true   # Enable SSL negotiation. Optional
#       useStartTls:         true   # Enable TLS negotiation. Optional
#       accountCanonicalForm: 3 # ACCTNAME_FORM_BACKSLASH this is only needed if your users have to login with something like HOST\User
#       accountDomainName: HOST
#       accountDomainNameShort: HOST # if you use the Backslash form set both to Hostname than the Username will be converted to HOST\User
#    user:
#        baseDn: ou=users, dc=admc, dc=com
#        filter: (&(ObjectClass=Person))
#        usernameAttribute: cn # Optional
#        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
#           - { ldap_attr: givenName,   user_method: setName }     # Optional
#
#           - { ldap_attr: mail,  user_method: setEmail }         # Optional
#   service:
#       user_hydrator: fr3d_ldap.user_hydrator.default # Overrides default user hydrator
#       ldap_manager: fr3d_ldap.ldap_manager.default   # Overrides default ldap manager
#       ldap_driver: fr3d_ldap.ldap_driver.zend        # Overrides default ldap driver