# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
       
    login_listener:
        class: 'ADMC\CoreBundle\Listener\LoginListener'
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            - { name: 'kernel.listener', event: 'fos_user.security.implicit_login' }

    my_password_encoder:
         class: 'ADMC\CoreBundle\LdapServices\MyPasswordEncoder'
         
    ldap_connect:
         class: 'ADMC\CoreBundle\LdapServices\ADMCConnector'
         
    ldap_list_all_users:
         class: 'ADMC\CoreBundle\LdapServices\ADMCSearchAllUsers' 
         arguments: ['@ldap_connect']
         
    ldap_list_user_by_group:
         class: 'ADMC\CoreBundle\LdapServices\ADMCListUserByGroup'
         arguments: ['@ldap_connect']
         

    ldap_update_database:
         class: 'ADMC\CoreBundle\LdapServices\ADMCMajBdd' 
         arguments: [@ldap_connect, @doctrine.orm.entity_manager, @ldap_list_all_users, @fos_user.user_manager, @fos_user.group_manager]
         
    ldap_insert_user:
         class: 'ADMC\CoreBundle\LdapServices\ADMCCreateuser'
         arguments: ['@ldap_connect']
         
    ldap_is_in_group:
         class: 'ADMC\CoreBundle\LdapServices\ADMCIsInGroup'
         arguments: ['@ldap_list_user_by_group']
  
    ldap_insert_user_in_group:
         class: 'ADMC\CoreBundle\LdapServices\ADMCAddgroup'
         arguments: ['@ldap_connect', @ldap_is_in_group]
         
    ldap_delete_user_from_group:
         class: 'ADMC\CoreBundle\LdapServices\ADMCDelUserFromGroup'
         arguments: ['@ldap_connect']
         
    ldap_list_group_by_user:
         class: 'ADMC\CoreBundle\LdapServices\ADMCListGroupByUser'
         arguments: ['@ldap_connect']
         
    ldap_modify_user:
         class: 'ADMC\CoreBundle\LdapServices\ADMCModifyUser'
         arguments: ['@ldap_connect']
         
    ldap_validate_request:
         class: 'ADMC\CoreBundle\LdapServices\ADMCValidateRequest'
         arguments: [@ldap_insert_user, @ldap_insert_user_in_group, @ldap_delete_user_from_group, @fos_user.user_manager, @fos_user.group_manager, @doctrine.orm.entity_manager, @security.context]
         
         
         
    ldap_delete_user:
         class: 'ADMC\CoreBundle\LdapServices\ADMCDeleteUser'
         arguments: [@ldap_connect, @fos_user.user_manager]
         
    ldap_remove_user_from_group:
         class: 'ADMC\CoreBundle\LdapServices\ADMCRemoveUserFromGroup'
         arguments: [@ldap_connect, @ldap_is_in_group]
         
    