<?php

namespace ADMC\CoreBundle\Repository;

/**
 * RoleRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
