admc_core_admin_groups:
    resource: "@ADMCCoreBundle/Resources/config/routing/group.yml"
    prefix:   /admin/groups
    
    
admc_core_admin_users:
    resource: "@ADMCCoreBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users


admc_core_homepage:
    path:     /
    defaults: { _controller: ADMCCoreBundle:Base:index }

admc_core_rh:
    path:     /rh
    defaults: { _controller: ADMCCoreBundle:Base:rh}


admc_core_request:
    path:     /request
    defaults: { _controller: ADMCCoreBundle:Base:request}
    
admc_core_adduser:
    path:     /adduser
    defaults: { _controller: ADMCCoreBundle:Base:addUser}


admc_core_adduser_group:
    path:     /addgroup
    defaults: { _controller: ADMCCoreBundle:Base:addGroup}
    
admc_core_list_user_by_group:
    path:     /listGroup
    defaults: { _controller: ADMCCoreBundle:Base:listGroup }
    
admc_core_modify_user:
    path:     /modifyUser
    defaults: { _controller: ADMCCoreBundle:Base:modifyUser }
    
admc_core_delete_user:
    path:     /deleteUser
    defaults: { _controller: ADMCCoreBundle:Base:deleteUser }
    
admc_core_delete_user_from_group:
    path:     /deleteUserFromGroup
    defaults: { _controller: ADMCCoreBundle:Base:deleteUserFromGroup }
    
admc_core_access_denied:
    path:     /accessDenied
    defaults: { _controller: ADMCCoreBundle:Base:denied }

admc_core_mail_sender:
    path:     /mailsender
    defaults: { _controller: ADMCCoreBundle:Base:mailsender }