admcdsi_homepage:
    path:     /
    defaults: { _controller: ADMCDSIBundle:Dsi:index }
   
admcdsi_request_list:
    path:     /list
    defaults: { _controller: ADMCDSIBundle:Dsi:requestsview }
    
admcdsi_request_refresh_list:
    path:     /listRefresh
    defaults: { _controller: ADMCDSIBundle:Dsi:requestList }
    
admcdsi_processed_list:
    path:     /processed
    defaults: { _controller: ADMCDSIBundle:Dsi:processedView}

admcdsi_processed_refresh_list:
    path:     /processedRefresh
    defaults: { _controller: ADMCDSIBundle:Dsi:processedList }
    
admcdsi_request_consult:
    path:     /consultRequest/?{id}
    defaults: { _controller: ADMCDSIBundle:Dsi:consultRequest }
    
admcdsi_request_consult_id:
    path:     /consultRequest/{id}
    defaults: { _controller: ADMCDSIBundle:Dsi:consultRequest }
    
admcdsi_validate_request:
    path:     /validateRequest/{id}
    defaults: { _controller: ADMCDSIBundle:Dsi:validateRequest }

admcdsi_refuse_request:
    path:     /refuseRequest/{id}
    defaults: { _controller: ADMCDSIBundle:Dsi:refuseRequest }
    
